# Generated by Django 4.2.10 on 2024-03-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebroom1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('startTime', models.TimeField()),
                ('endDate', models.DateField()),
                ('endTime', models.TimeField()),
            ],
        ),
    ]
