# Generated by Django 4.2.10 on 2024-03-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebroom1', '0004_person_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
            ],
        ),
    ]
